#!/bin/bash
shopt -s nullglob
if [[ -z "$LEMMI16s_ROOT" ]]; then
    echo "Must set LEMMI16s_ROOT in environment" 1>&2
    exit 1
fi

dt=$(date +%s)

if (echo 7.8.0; snakemake --version ) | sort -Vr | tail -n 1 | grep -q "7.8.0"
then
    rerun="--rerun-triggers mtime"
else
    rerun=""
fi


echo "Setting up the repository..."
snakemake ${rerun} --singularity-args "-B $LEMMI16s_ROOT:$LEMMI16s_ROOT" --rerun-incomplete --printshellcmds --snakefile ${LEMMI16s_ROOT}/workflow/rules/repository.smk --configfile ${LEMMI16s_ROOT}/config/config.yaml --directory ${LEMMI16s_ROOT} --reason --config datetime=$dt $@

echo "LEMMI16s DONE"


